=== richardRadli/Multi_Phase_Deep_Random_Neural_Network/config/MPDRNN_config_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "MPDRNN config",
  "type": "object",
  "properties": {
    "dataset_name": {
      "type": "string",
      "enum": ["connect4", "isolete", "letter", "mnist", "mnist_fashion", "musk2", "optdigits", "page_blocks", "satimages", "segment", "shuttle", "spambase", "usps"],
      "description": "The name of the dataset to be used."
    },
    "activation": {
      "type": "string",
      "enum": ["ReLU", "LeakyReLU", "Tanh", "Sigmoid", "Identity"],
      "description": "The activation function to be used in the neural network."
    },
    "number_of_tests": {
      "type": "integer",
      "description": "Number of tests to be performed."
    },
    "seed": {
      "type": "boolean",
      "description": "Controls the way to generate random values. If set to True, the same values will be generated in every execution."
    },
    "method": {
      "type": "string",
      "enum": ["BASE", "EXP_ORT", "EXP_ORT_C"],
      "description": "The method to generate new weights in consecutive layers."
    },
    "mu": {
      "type": "number",
      "const": 0,
      "description": "The mean of a uniform distribution is the midpoint of the interval."
    },
    "sigma": {
      "type": "number",
      "default": 0.15,
      "description": "The standard deviation of a uniform distribution is a measure of the spread of the distribution."
    },
    "eq_neurons": {
      "type": "object",
      "description": "Number of equal neurons.",
      "properties": {
        "connect4": {
          "type": "array"
        },
        "isolete": {
          "type": "array"
        },
        "letter": {
          "type": "array"
        },
        "mnist": {
          "type": "array"
        },
        "mnist_fashion": {
          "type": "array"
        },
        "musk2": {
          "type": "array"
        },
        "optdigits": {
          "type": "array"
        },
        "page_blocks": {
          "type": "array"
        },
        "satimages": {
          "type": "array"
        },
        "segment": {
          "type": "array"
        },
        "shuttle": {
          "type": "array"
        },
        "spambase": {
          "type": "array"
        },
        "usps": {
          "type": "array"
        }
      }
    },
    "exp_neurons": {
      "type": "object",
      "description": "Number of equal neurons.",
      "properties": {
        "connect4": {
          "type": "array"
        },
        "isolete": {
          "type": "array"
        },
        "letter": {
          "type": "array"
        },
        "mnist": {
          "type": "array"
        },
        "mnist_fashion": {
          "type": "array"
        },
        "musk2": {
          "type": "array"
        },
        "optdigits": {
          "type": "array"
        },
        "page_blocks": {
          "type": "array"
        },
        "satimages": {
          "type": "array"
        },
        "segment": {
          "type": "array"
        },
        "shuttle": {
          "type": "array"
        },
        "spambase": {
          "type": "array"
        },
        "usps": {
          "type": "array"
        }
      }
    }
  },
  "required": ["dataset_name", "activation", "number_of_tests", "seed", "method"]
}

=== richardRadli/Multi_Phase_Deep_Random_Neural_Network/config/MPDRNN_config.json
{
  "dataset_name": "satimages",
  "activation": "LeakyReLU",
  "number_of_tests": 50,
  "seed": true,
  "method": "EXP_ORT",
  "mu": 0,
  "sigma": 0.1,
  "eq_neurons": {
    "connect4": [866, 866, 866],
    "isolete": [1050, 1050, 1050],
    "letter": [1200, 1200, 1200],
    "mnist": [5333, 5333, 5333],
    "mnist_fashion": [2000, 2000, 2000],
    "musk2": [520, 520, 520],
    "optdigits": [216, 216, 216],
    "page_blocks": [216, 216, 216],
    "satimages": [250, 250, 250],
    "segment": [216, 216, 216],
    "shuttle": [216, 216, 216],
    "spambase": [216, 216, 216],
    "usps": [866, 866, 866]
  },
  "exp_neurons": {
    "connect4": [2049, 452, 100],
    "isolete": [2000, 1500, 600],
    "letter": [2000, 1000, 600],
    "mnist": [8000, 5000, 3000],
    "mnist_fashion": [8000, 5000, 3000],
    "musk2": [1500, 750, 350],
    "optdigits": [325, 325, 325],
    "page_blocks": [300, 200, 100],
    "satimages": [2000, 1000, 600],
    "segment": [220, 220, 220],
    "shuttle": [400, 200, 50],
    "spambase": [400, 200, 50],
    "usps": [2049, 452, 100]
  }
}
